# Default values for api-helm-chart.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: talk2toks/alef-challenge
  tag: v0.0.10
  pullPolicy: Always
service:
  name: api
  externalPort: 80
  internalPort: 5000
  port: 5000
  targetPort: 5000
  type: NodePort
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "100m"
livenessProbe:
  httpGet:
    failureThreshold: 1
    periodSeconds: 10
    path: /healthz
readinessProbe:
  httpGet:
    failureThreshold: 30
    periodSeconds: 10
    path: /healthz
mongodb:
  MONGODB_HOSTNAME: "mongodb"
  MONGODB_DATABASE: "task"